"use client";
import { FormEvent, useState } from "react";
import { Icon } from "../../../components/Icon";
import { useSystem } from "../../../components/system/SystemProvider";

type EquipmentForm = { tag: string; name: string; companyId: string; category: string; next: string };
const empty: EquipmentForm = { tag: "", name: "", companyId: "", category: "Vaso de pressão", next: "" };
const inputDate = (value: string) => { const [day, month, year] = value.split("/"); return year ? `${year}-${month}-${day}` : ""; };

export default function Equipment() {
  const { companies, equipment, companyFilter, addEquipment, updateEquipment, deleteEquipment } = useSystem();
  const [open, setOpen] = useState(false); const [editing, setEditing] = useState<string | null>(null); const [value, setValue] = useState<EquipmentForm>(empty); const [error, setError] = useState("");
  const visible = equipment.filter(item => companyFilter === "all" || item.companyId === companyFilter);
  function start(id?: string) { const item = id ? equipment.find(entry => entry.id === id) : undefined; setEditing(id ?? null); setValue(item ? { tag: item.tag, name: item.name, companyId: item.companyId, category: item.category, next: inputDate(item.next) } : { ...empty, companyId: companies[0]?.id ?? "" }); setError(""); setOpen(true); }
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); try { if (editing) await updateEquipment(editing, { ...value, status: "Em dia" }); else await addEquipment({ ...value, status: "Em dia" }); setOpen(false); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível salvar o equipamento"); } }
  async function remove(id: string) { if (!window.confirm("Excluir este equipamento? A exclusão só é possível sem inspeções vinculadas.")) return; setError(""); try { await deleteEquipment(id); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível excluir o equipamento"); } }
  return <><div className="pageHead"><div><small>ATIVOS NR-13</small><h1>Equipamentos</h1><p>Cadastro essencial dos equipamentos inspecionados.</p></div><button className="primary" onClick={() => start()}><Icon name="plus" />Novo equipamento</button></div><section className="panel"><div className="cardsList">{visible.map(item => <article key={item.id}><div className="assetIcon"><Icon name="equipment" /></div><div className="grow"><small>{item.tag} · {item.category}</small><h3>{item.name}</h3><p>{companies.find(company => company.id === item.companyId)?.name}</p></div><div className="assetDate"><small>PRÓXIMA INSPEÇÃO</small><b>{item.next}</b></div><span className={`badge ${item.status === "Vencido" ? "red" : item.status === "Atenção" ? "amber" : "green"}`}>{item.status}</span><span className="rowActions"><button className="secondaryBtn" onClick={() => start(item.id)}>Editar</button><button className="secondaryBtn" onClick={() => remove(item.id)}>Excluir</button></span></article>)}</div>{error && <p className="formError">{error}</p>}</section>{open && <div className="modal" onMouseDown={() => setOpen(false)}><form className="dialog" onSubmit={submit} onMouseDown={event => event.stopPropagation()}><div className="panelHead"><div><small>{editing ? "EDITAR ATIVO" : "NOVO ATIVO"}</small><h2>{editing ? "Editar equipamento" : "Cadastrar equipamento"}</h2></div><button type="button" className="close" onClick={() => setOpen(false)}>×</button></div><label>Empresa<select required name="company" value={value.companyId} onChange={event => setValue({ ...value, companyId: event.target.value })}>{companies.map(company => <option value={company.id} key={company.id}>{company.name}</option>)}</select></label><div className="formGrid"><label>TAG<input required name="tag" value={value.tag} onChange={event => setValue({ ...value, tag: event.target.value })} placeholder="VP-001" /></label><label>Categoria<select name="category" value={value.category} onChange={event => setValue({ ...value, category: event.target.value })}><option>Vaso de pressão</option><option>Caldeira</option><option>Tubulação</option></select></label></div><label>Nome do equipamento<input required name="name" value={value.name} onChange={event => setValue({ ...value, name: event.target.value })} placeholder="Ex.: Vaso pulmão de ar" /></label><label>Próxima inspeção<input required name="next" value={value.next} onChange={event => setValue({ ...value, next: event.target.value })} type="date" /></label>{error && <p className="formError">{error}</p>}<button className="primary" type="submit"><Icon name="save" />{editing ? "Salvar alterações" : "Salvar equipamento"}</button></form></div>}</>;
}