"use client";
import { FormEvent, useState } from "react";
import { Icon } from "../../../components/Icon";
import { useSystem } from "../../../components/system/SystemProvider";

type CompanyForm = { name: string; cnpj: string; city: string; state: string; contact: string };
const empty: CompanyForm = { name: "", cnpj: "", city: "", state: "", contact: "" };

export default function Companies() {
  const { companies, equipment, addCompany, updateCompany, deleteCompany } = useSystem();
  const [open, setOpen] = useState(false);
  const [editing, setEditing] = useState<string | null>(null);
  const [value, setValue] = useState<CompanyForm>(empty);
  const [error, setError] = useState("");
  const [busy, setBusy] = useState(false);
  function start(id?: string) { const company = id ? companies.find(item => item.id === id) : undefined; const [city, state = ""] = (company?.city ?? "").split("/"); setEditing(id ?? null); setValue(company ? { name: company.name, cnpj: company.cnpj, city: city.trim(), state: state.trim(), contact: company.contact } : empty); setError(""); setOpen(true); }
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); const form = new FormData(event.currentTarget); const data = { name: String(form.get("name")), cnpj: String(form.get("cnpj")), city: `${String(form.get("city")).trim()}/${String(form.get("state")).trim().toUpperCase()}`, contact: String(form.get("contact")) }; try { if (editing) await updateCompany(editing, data); else await addCompany(data); setOpen(false); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível salvar a empresa"); } finally { setBusy(false); } }
  async function remove(id: string) { if (!window.confirm("Excluir esta empresa? A exclusão só é possível sem equipamentos vinculados.")) return; setError(""); try { await deleteCompany(id); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível excluir a empresa"); } }
  return <><div className="pageHead"><div><small>CADASTROS</small><h1>Empresas</h1><p>Clientes e locais sob sua responsabilidade.</p></div><button className="primary" onClick={() => start()}><Icon name="plus" />Nova empresa</button></div><section className="panel"><div className="table"><div className="tr th"><span>Empresa</span><span>CNPJ</span><span>Cidade</span><span>Equipamentos</span><span>Ações</span></div>{companies.map(company => <div className="tr" key={company.id}><span><b>{company.name}</b><small>{company.contact}</small></span><span>{company.cnpj}</span><span>{company.city}</span><span>{equipment.filter(item => item.companyId === company.id).length}</span><span className="rowActions"><button className="secondaryBtn" onClick={() => start(company.id)}>Editar</button><button className="secondaryBtn" onClick={() => remove(company.id)}>Excluir</button></span></div>)}</div>{error && <p className="formError">{error}</p>}</section>{open && <div className="modal" onMouseDown={() => !busy && setOpen(false)}><form className="dialog" onSubmit={submit} onMouseDown={event => event.stopPropagation()}><div className="panelHead"><div><small>{editing ? "EDITAR CADASTRO" : "NOVO CADASTRO"}</small><h2>{editing ? "Editar empresa" : "Adicionar empresa"}</h2></div><button type="button" className="close" onClick={() => setOpen(false)}>×</button></div><label>Razão social<input required name="name" value={value.name} onChange={event => setValue({ ...value, name: event.target.value })} placeholder="Nome da empresa" /></label><div className="formGrid"><label>CNPJ<input required name="cnpj" value={value.cnpj} onChange={event => setValue({ ...value, cnpj: event.target.value })} placeholder="00.000.000/0000-00" pattern="[0-9.\-]{14,18}" /></label><label>Cidade<input required name="city" value={value.city} onChange={event => setValue({ ...value, city: event.target.value })} placeholder="Contagem" /></label><label>UF<input required name="state" value={value.state} onChange={event => setValue({ ...value, state: event.target.value })} maxLength={2} minLength={2} pattern="[A-Za-z]{2}" placeholder="MG" /></label></div><label>Contato responsável<input required name="contact" value={value.contact} onChange={event => setValue({ ...value, contact: event.target.value })} placeholder="Nome do contato" /></label>{error && <p className="formError">{error}</p>}<button className="primary" type="submit" disabled={busy}><Icon name="save" />{busy ? "Salvando…" : editing ? "Salvar alterações" : "Salvar empresa"}</button></form></div>}</>;
}
