"use client";
import { useEffect, useMemo, useState } from "react";
import { useAuth } from "./auth/AuthProvider";

type Manufacturer={id:string;name:string};
const clean=(value:string)=>value.normalize("NFKC").trim().replace(/\s+/g," ");
const key=(value:string)=>clean(value).toLocaleLowerCase("pt-BR");

export function ManufacturerCatalogField({value,onChange}:{value:string;onChange:(value:string)=>void}){
 const {request,user}=useAuth(); const [items,setItems]=useState<Manufacturer[]>([]); const [search,setSearch]=useState(""); const [open,setOpen]=useState(false); const [name,setName]=useState(""); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [success,setSuccess]=useState(""); const canCreate=user?.role!=="VIEWER";
 useEffect(()=>{let active=true;void request<Manufacturer[]>("/manufacturers").then(rows=>{if(active)setItems(rows)}).catch(x=>{if(active)setError(x instanceof Error?x.message:"Não foi possível carregar as marcas.")});return()=>{active=false}},[request]);
 const options=useMemo(()=>{const term=key(search);return items.filter(item=>!term||key(item.name).includes(term)||key(item.name)===key(value))},[items,search,value]); const legacy=value&&!items.some(item=>key(item.name)===key(value));
 const create=async()=>{const cleaned=clean(name);setError("");setSuccess("");if(cleaned.length<2){setError("Informe uma marca com pelo menos 2 caracteres.");return}if(items.some(item=>key(item.name)===key(cleaned))){setError("Esta marca já está cadastrada.");return}setBusy(true);try{const created=await request<Manufacturer>("/manufacturers",{method:"POST",body:JSON.stringify({name:cleaned})});setItems(current=>[...current,created].sort((a,b)=>a.name.localeCompare(b.name,"pt-BR")));onChange(created.name);setSearch("");setName("");setSuccess(`Marca ${created.name} cadastrada com sucesso.`);setOpen(false)}catch(x){setError(x instanceof Error?x.message:"Não foi possível cadastrar a marca.")}finally{setBusy(false)}};
 return <div className="manufacturerCatalog"><input aria-label="Buscar marca" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar no catálogo"/><select aria-label="Selecionar marca" value={value} onChange={e=>onChange(e.target.value)}><option value="">Selecione uma marca</option>{legacy&&<option value={value}>{value} (registro existente)</option>}{options.map(item=><option value={item.name} key={item.id}>{item.name}</option>)}</select>{canCreate&&<button className="secondaryBtn manufacturerAdd" type="button" onClick={()=>{setOpen(true);setError("");setSuccess("")}}>Cadastrar nova marca</button>}{error&&<p className="formError manufacturerFeedback" role="alert">{error}</p>}{success&&<p className="formSuccess manufacturerFeedback" role="status">{success}</p>}{open&&<div className="modal" onMouseDown={()=>setOpen(false)}><div className="dialog manufacturerDialog" role="dialog" aria-modal="true" aria-labelledby="manufacturer-title" onMouseDown={event=>event.stopPropagation()}><div className="panelHead"><div><small>CATÁLOGO DO WORKSPACE</small><h2 id="manufacturer-title">Cadastrar nova marca</h2></div><button type="button" className="close" aria-label="Fechar" onClick={()=>setOpen(false)}>×</button></div><label>Nome da marca<input autoFocus maxLength={80} value={name} onChange={e=>setName(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();void create()}}} placeholder="Ex.: Schulz"/></label>{error&&<p className="formError" role="alert">{error}</p>}<button className="primary" type="button" disabled={busy} onClick={()=>void create()}>{busy?"Salvando…":"Salvar no catálogo"}</button></div></div>}</div>
}
