"use client";
import { calculatePmta, PMTA_CODE, PMTA_FORMULA, PMTA_GEOMETRY, PMTA_METHOD, PmtaCalculation } from "../lib/pmta";

const numberValue=(value:number|undefined)=>Number.isFinite(value)?String(value):"";
export function PmtaCalculationPanel({value,onChange}:{value:PmtaCalculation;onChange:(value:PmtaCalculation)=>void}){
 const calculated=value.mode==="CALCULATED";let preview:ReturnType<typeof calculatePmta>|null=null,error="";
 if(calculated)try{preview=calculatePmta(value)}catch(cause){error=cause instanceof Error?cause.message:"Premissas inválidas."}
 const update=(patch:Partial<PmtaCalculation>)=>{let next={...value,...patch};if(next.mode==="CALCULATED"){next={...next,code:PMTA_CODE,method:PMTA_METHOD,geometry:PMTA_GEOMETRY,formula:PMTA_FORMULA};try{const result=calculatePmta(next);next={...next,...result,memory:`Espessura efetiva: ${result.effectiveThicknessMm} mm. Critério circunferencial: ${result.circumferentialResultBar} bar. Critério longitudinal: ${result.longitudinalResultBar} bar. Resultado adotado (menor): ${result.adoptedResultBar} bar.`}}catch{next={...next,circumferentialResultBar:undefined,longitudinalResultBar:undefined,adoptedResultBar:undefined,memory:""}}}onChange(next)};
 const numeric=(key:keyof PmtaCalculation,label:string,unit:string,step="0.001")=><label className="inspectionField"><span>{label} ({unit})</span><input type="number" min="0" step={step} value={numberValue(value[key] as number|undefined)} onChange={event=>update({[key]:event.target.value===""?undefined:Number(event.target.value)})}/></label>;
 return <div className="pmtaPanel"><div className="subhead"><h3>Pressão Máxima de Trabalho Admissível (PMTA)</h3></div><div className="pmtaModes"><label><input type="radio" checked={calculated} onChange={()=>update({mode:"CALCULATED",code:PMTA_CODE,method:PMTA_METHOD,geometry:PMTA_GEOMETRY,reason:""})}/>Calcular PMTA</label><label><input type="radio" checked={!calculated} onChange={()=>onChange({mode:"NOT_CALCULATED",reason:""})}/>Sem cálculo de PMTA</label></div>{calculated?<><p className="technicalNote">Escopo suportado: ASME VIII Div. 1 / UG-27, casco cilíndrico sob pressão interna. Unidades: mm, MPa e bar.</p><div className="inspectionGrid"><label className="inspectionField"><span>Código</span><input readOnly value={PMTA_CODE}/></label><label className="inspectionField"><span>Método</span><input readOnly value={PMTA_METHOD}/></label><label className="inspectionField"><span>Edição do código</span><input required value={value.edition||""} onChange={event=>update({edition:event.target.value})} placeholder="Ex.: 2025"/></label>{numeric("measuredThicknessMm","Espessura medida","mm")}{numeric("corrosionAllowanceMm","Margem de corrosão","mm")}{numeric("insideRadiusMm","Raio interno","mm")}{numeric("allowableStressMpa","Tensão admissível","MPa")}{numeric("jointEfficiency","Eficiência de junta","0–1","0.001")}</div><div className="pmtaFormula"><small>FÓRMULA</small><code>{PMTA_FORMULA}</code>{error?<p className="formError">{error}</p>:preview&&<><p>Espessura efetiva: <b>{preview.effectiveThicknessMm} mm</b></p><p>Critério circunferencial: <b>{preview.circumferentialResultBar} bar</b></p><p>Critério longitudinal: <b>{preview.longitudinalResultBar} bar</b></p><strong>PMTA adotada: {preview.adoptedResultBar} bar</strong></>}</div></>:<label className="inspectionField pmtaReason"><span>Motivo / referência da memória externa (opcional)</span><textarea value={value.reason||""} onChange={event=>update({reason:event.target.value})} placeholder="Ex.: cálculo não realizado nesta inspeção; consultar prontuário do equipamento."/><b>PMTA não calculada nesta inspeção.</b></label>}</div>;
}
