"use client";
import { createContext, useCallback, useContext, useEffect, useState } from "react";
type User={id:string;name:string;email:string;role:string;crea?:string;tenant:{id:string;name:string;slug:string;plan:string;status:string}};
type Auth={user:User|null;loading:boolean;request:<T>(path:string,init?:RequestInit)=>Promise<T>;save:(data:{accessToken:string;refreshToken:string;user:User})=>void;logout:()=>Promise<void>};
const Context=createContext<Auth|null>(null); const API=process.env.NEXT_PUBLIC_API_URL||(process.env.NODE_ENV==="production"?"https://api.nrnexus.com.br":"http://localhost:3333");
export function AuthProvider({children}:{children:React.ReactNode}){const [user,setUser]=useState<User|null>(null);const [loading,setLoading]=useState(true);
 const save=useCallback((d:{accessToken:string;refreshToken:string;user:User})=>{localStorage.setItem("nexus-auth",JSON.stringify(d));setUser(d.user)},[]);
 const refresh=useCallback(async()=>{const raw=localStorage.getItem("nexus-auth");if(!raw)return null;const old=JSON.parse(raw);const res=await fetch(`${API}/v1/auth/refresh`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({refreshToken:old.refreshToken})});if(!res.ok){localStorage.removeItem("nexus-auth");setUser(null);return null}const data=await res.json();save(data);return data.accessToken},[save]);
 const request=useCallback(async<T,>(path:string,init:RequestInit={})=>{const raw=localStorage.getItem("nexus-auth");let token=raw?JSON.parse(raw).accessToken:null;let res=await fetch(`${API}/v1${path}`,{...init,headers:{"content-type":"application/json",...init.headers,...(token?{authorization:`Bearer ${token}`}:{})}});if(res.status===401&&raw){token=await refresh();if(token)res=await fetch(`${API}/v1${path}`,{...init,headers:{"content-type":"application/json",...init.headers,authorization:`Bearer ${token}`}})}if(!res.ok){const body=await res.json().catch(()=>({}));const message=body?.error?.message;throw new Error(Array.isArray(message)?message.join(", "):typeof message==="string"?message:typeof body.error==="string"?body.error:`Não foi possível concluir (${res.status})`)};return res.json() as Promise<T>},[refresh]);
 const logout=useCallback(async()=>{const raw=localStorage.getItem("nexus-auth");if(raw){const d=JSON.parse(raw);await fetch(`${API}/v1/auth/logout`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({refreshToken:d.refreshToken})}).catch(()=>{})}localStorage.removeItem("nexus-auth");setUser(null)},[]);
 useEffect(()=>{void Promise.resolve().then(async()=>{const raw=localStorage.getItem("nexus-auth");if(!raw){setLoading(false);return}try{setUser(await request<User>("/auth/me"))}catch{localStorage.removeItem("nexus-auth");setUser(null)}finally{setLoading(false)}})},[request]);return <Context.Provider value={{user,loading,request,save,logout}}>{children}</Context.Provider>}
export function useAuth(){const v=useContext(Context);if(!v)throw new Error("AuthProvider ausente");return v}
