"use client";
import { ChangeEvent, FormEvent, useEffect, useState } from "react";
import { Icon } from "../../../components/Icon";
import { User, useAuth } from "../../../components/auth/AuthProvider";
import styles from "./settings.module.css";

type Settings = User & { tenant: User["tenant"] };
const readImage = (event: ChangeEvent<HTMLInputElement>, setValue: (value: string) => void) => { const file = event.target.files?.[0]; if (!file) return; if (file.size > 1_500_000) { window.alert("Escolha uma imagem de até 1,5 MB."); return; } const reader = new FileReader(); reader.onload = () => setValue(String(reader.result)); reader.readAsDataURL(file); };

export default function SettingsPage() {
  const { user, request, updateUser } = useAuth();
  const [settings, setSettings] = useState<Settings | null>(null); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { if (user) void request<Settings>("/settings").then(setSettings).catch(cause => setError(cause instanceof Error ? cause.message : "Não foi possível carregar as configurações")); }, [user, request]);
  if (!settings) return <div className="pageHead"><div><small>CONFIGURAÇÕES</small><h1>Carregando…</h1></div></div>;
  const current = settings;
  const canEditWorkspace = ["OWNER", "ADMIN"].includes(settings.role);
  async function saveProfile(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage(""); setError(""); const form = new FormData(event.currentTarget); try { const next = await request<Settings>("/settings/profile", { method: "PATCH", body: JSON.stringify({ name: form.get("name"), phone: form.get("phone"), crea: form.get("crea"), avatarUrl: current.avatarUrl }) }); setSettings(next); updateUser(next); setMessage("Perfil atualizado."); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível salvar o perfil"); } finally { setBusy(false); } }
  async function saveWorkspace(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage(""); setError(""); const form = new FormData(event.currentTarget); try { const tenant = await request<User["tenant"]>("/settings/workspace", { method: "PATCH", body: JSON.stringify({ name: form.get("name"), billingEmail: form.get("billingEmail") || undefined, paymentMethod: form.get("paymentMethod") || undefined, logoUrl: current.tenant.logoUrl }) }); const next = { ...current, tenant }; setSettings(next); updateUser(next); setMessage("Workspace atualizado."); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível salvar o workspace"); } finally { setBusy(false); } }
  const setAvatar = (value: string) => setSettings({ ...current, avatarUrl: value }); const setLogo = (value: string) => setSettings({ ...current, tenant: { ...current.tenant, logoUrl: value } });
  return <><div className="pageHead"><div><small>CONTA E WORKSPACE</small><h1>Configurações</h1><p>Gerencie seu perfil, a identidade da empresa e a preferência de cobrança.</p></div></div><div className={styles.settingsGrid}><section className={`panel ${styles.settingsPanel}`}><div className="panelHead"><div><h2>Seu perfil</h2><p>Esses dados aparecem para sua equipe.</p></div></div><form onSubmit={saveProfile}><div className={styles.imageSetting}><div className={styles.imagePreview}>{settings.avatarUrl ? <img src={settings.avatarUrl} alt="Foto de perfil" /> : <span>{settings.name.slice(0, 2).toUpperCase()}</span>}</div><label className={styles.uploadButton}>Alterar foto<input type="file" accept="image/*" onChange={event => readImage(event, setAvatar)} /></label></div><label>Nome<input required name="name" defaultValue={settings.name} /></label><label>E-mail<input disabled value={settings.email} readOnly /></label><label>Telefone<input name="phone" defaultValue={settings.phone ?? ""} placeholder="(00) 00000-0000" /></label><label>CREA<input name="crea" defaultValue={settings.crea ?? ""} /></label><button className="primary" disabled={busy}><Icon name="save" />Salvar perfil</button></form></section><section className={`panel ${styles.settingsPanel}`}><div className="panelHead"><div><h2>Identidade da empresa</h2><p>Logo exibida no menu e nos próximos documentos.</p></div></div><form onSubmit={saveWorkspace}><div className={styles.imageSetting}><div className={styles.logoPreview}>{settings.tenant.logoUrl ? <img src={settings.tenant.logoUrl} alt="Logo da empresa" /> : <span>N</span>}</div><label className={styles.uploadButton}>Alterar logo<input disabled={!canEditWorkspace} type="file" accept="image/*" onChange={event => readImage(event, setLogo)} /></label></div><label>Nome do workspace<input disabled={!canEditWorkspace} required name="name" defaultValue={settings.tenant.name} /></label><label>E-mail de cobrança<input disabled={!canEditWorkspace} type="email" name="billingEmail" defaultValue={settings.tenant.billingEmail ?? ""} placeholder="financeiro@empresa.com" /></label><label>Método de cobrança recorrente<select disabled={!canEditWorkspace} name="paymentMethod" defaultValue={settings.tenant.paymentMethod ?? ""}><option value="">Não definido</option><option value="CREDIT_CARD">Cartão de crédito</option><option value="PIX">PIX recorrente</option><option value="BOLETO">Boleto recorrente</option></select></label><small className="formHint">Nenhum número de cartão é armazenado aqui. A cobrança será conectada ao gateway de pagamentos.</small><button className="primary" disabled={busy || !canEditWorkspace}><Icon name="save" />Salvar empresa e cobrança</button></form></section></div>{message&&<p className="authSuccess">{message}</p>}{error&&<p className="formError">{error}</p>}</>;
}