"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { useAuth } from "@/components/auth/AuthProvider";
type Member={id:string;name:string;email:string;role:string;crea?:string;active:boolean};
export default function Team(){
 const {request}=useAuth(); const [members,setMembers]=useState<Member[]>([]); const [error,setError]=useState(""); const [invite,setInvite]=useState("");
 const load=useCallback(()=>request<Member[]>("/users").then(setMembers).catch(e=>setError(e.message)),[request]); useEffect(()=>{void load()},[load]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{const d=await request<{invitationToken:string}>("/users/invitations",{method:"POST",body:JSON.stringify(Object.fromEntries(f))});setInvite(`${location.origin}/convite?token=${d.invitationToken}`);e.currentTarget.reset()}catch(x){setError(x instanceof Error?x.message:"Falha ao convidar")}}
 async function update(id:string,data:object){try{await request(`/users/${id}`,{method:"PATCH",body:JSON.stringify(data)});await load()}catch(x){setError(x instanceof Error?x.message:"Falha ao atualizar")}}
 return <><div className="pageHead"><div><small>WORKSPACE</small><h1>Equipe e acessos</h1><p>Convide pessoas e controle papéis sem misturar dados entre organizações.</p></div></div><div className="teamGrid"><section className="panel teamInvite"><div className="panelHead"><div><h2>Convidar usuário</h2><p>O link expira em 7 dias</p></div></div><form onSubmit={submit}><label>E-mail<input required type="email" name="email"/></label><label>Papel<select name="role" defaultValue="INSPECTOR"><option value="ADMIN">Administrador</option><option value="ENGINEER">Engenheiro</option><option value="INSPECTOR">Inspetor</option><option value="VIEWER">Visualizador</option></select></label><button className="primary">Gerar convite</button></form>{invite&&<div className="inviteLink"><small>LINK LOCAL DE CONVITE</small><input readOnly value={invite}/></div>}{error&&<p className="formError">{error}</p>}</section><section className="panel"><div className="panelHead"><div><h2>Usuários</h2><p>{members.length} pessoas no workspace</p></div></div><div className="teamList">{members.map(m=><article key={m.id}><span>{m.name.slice(0,2).toUpperCase()}</span><div><b>{m.name}</b><small>{m.email}{m.crea?` · CREA ${m.crea}`:""}</small></div><select value={m.role} disabled={m.role==="OWNER"} onChange={e=>update(m.id,{role:e.target.value})}><option>OWNER</option><option>ADMIN</option><option>ENGINEER</option><option>INSPECTOR</option><option>VIEWER</option></select><button className="secondaryBtn" disabled={m.role==="OWNER"} onClick={()=>update(m.id,{active:!m.active})}>{m.active?"Desativar":"Ativar"}</button></article>)}</div></section></div></>
}
